export const SET = 'SET';
export const CLOSE_FILE_CONTROL_LIST = 'CLOSE_FILE_CONTROL_LIST';
export const OPEN_PROGRESS_BAR_DIALOG = 'OPEN_PROGRESS_BAR_DIALOG';
export const CLOSE_PROGRESS_BAR_DIALOG = 'CLOSE_PROGRESS_BAR_DIALOG';
export const SHOW_MESSANGE = 'SHOW_MESSANGE';
export const CLOSE_MESSANGE = 'CLOSE_MESSANGE';
export const UPLOAD = 'UPLOAD';
