export const REMOVE_CARD = 'REMOVE_CARD';
export const DROP_CARD = 'DROP_CARD';
export const CLICK_REMOVE_CARD = 'CLICK_REMOVE_CARD';
export const DROP_CARD_COLUMN = 'DROP_CARD_COLUMN';
export const WATCH_COLLECT_CARD = 'WATCH_COLLECT_CARD';
