export const SET_VALUE = 'SET_VALUE';
export const OPEN_FILE_CONTROL_LIST = 'OPEN_FILE_CONTROL_LIST';
export const CLOSE_FILE_CONTROL_LIST = 'CLOSE_FILE_CONTROL_LIST';
export const OPEN_PROGRESS_BAR_DIALOG = 'OPEN_PROGRESS_BAR_DIALOG';
export const CLOSE_PROGRESS_BAR_DIALOG = 'CLOSE_PROGRESS_BAR_DIALOG';
