export const SET_VALUE = 'SET_VALUE';
export const OPEN_FILE_CONTROL_LIST = 'OPEN_FILE_CONTROL_LIST';
export const CLOSE_FILE_CONTROL_LIST = 'CLOSE_FILE_CONTROL_LIST';
export const DROP_CARD_COLUMN = 'DROP_CARD_COLUMN';
export const WATCH_COLLECT_CARD = 'WATCH_COLLECT_CARD';
